// SPDX-License-Identifier: UNLICENSED

/*
    Tx Keeper Contract
    
    This contract serves as the event emitter for all balance operations in the Hunch Bridge system.
    All functions are restricted to admin only (withdraw server and main server share admin address).
    
    Events:
    - WithdrawalRequested: Emitted when user initiates withdrawal via withdraw server
    - DepositFinalized: Emitted when deposit is successfully processed by main server
    - WithdrawalFinalized: Emitted when withdrawal is successfully finalized by main server
    
    The tx-listener server listens to these events and updates user balances in MongoDB.
*/

pragma solidity ^0.8.9;

contract TxKeeper {
    // Events
    event WithdrawalRequested(
        address indexed user,
        address indexed destination,
        uint64 usd,
        uint64 nonce,
        uint256 timestamp
    );
    
    event DepositFinalized(
        address indexed user,
        uint64 usd,
        uint256 timestamp
    );
    
    event WithdrawalFinalized(
        address indexed user,
        address indexed destination,
        uint64 usd,
        uint64 nonce,
        uint256 timestamp
    );
    
    // State
    address public admin; // Admin address (withdraw server and main server)
    
    // Modifier
    modifier onlyAdmin() {
        require(msg.sender == admin, "TxKeeper: Only admin can call");
        _;
    }
    
    // Constructor
    constructor(address _admin) {
        require(_admin != address(0), "TxKeeper: Admin cannot be zero address");
        admin = _admin;
    }
    
    /**
     * @notice Request a withdrawal (called by withdraw server)
     * @param user User address requesting withdrawal
     * @param destination Destination address on Arbitrum
     * @param usd Amount in USDC (uint64)
     * @param nonce Withdrawal nonce (auto-generated by withdraw server)
     */
    function requestWithdrawal(
        address user,
        address destination,
        uint64 usd,
        uint64 nonce
    ) external onlyAdmin {
        require(user != address(0), "TxKeeper: User cannot be zero address");
        require(destination != address(0), "TxKeeper: Destination cannot be zero address");
        require(usd > 0, "TxKeeper: Amount must be greater than zero");
        
        emit WithdrawalRequested(user, destination, usd, nonce, block.timestamp);
    }
    
    /**
     * @notice Finalize a deposit (called by main server after validator quorum)
     * @param user User address who deposited
     * @param usd Amount in USDC (uint64)
     */
    function finalizeDeposit(
        address user,
        uint64 usd
    ) external onlyAdmin {
        require(user != address(0), "TxKeeper: User cannot be zero address");
        require(usd > 0, "TxKeeper: Amount must be greater than zero");
        
        emit DepositFinalized(user, usd, block.timestamp);
    }
    
    /**
     * @notice Finalize a withdrawal (called by main server after Bridge2 finalization)
     * @param user User address who requested withdrawal
     * @param destination Destination address on Arbitrum
     * @param usd Amount in USDC (uint64)
     * @param nonce Withdrawal nonce
     */
    function finalizeWithdrawal(
        address user,
        address destination,
        uint64 usd,
        uint64 nonce
    ) external onlyAdmin {
        require(user != address(0), "TxKeeper: User cannot be zero address");
        require(destination != address(0), "TxKeeper: Destination cannot be zero address");
        require(usd > 0, "TxKeeper: Amount must be greater than zero");
        
        emit WithdrawalFinalized(user, destination, usd, nonce, block.timestamp);
    }
    
    /**
     * @notice Update admin address (requires current admin)
     * @param _newAdmin New admin address
     */
    function updateAdmin(address _newAdmin) external onlyAdmin {
        require(_newAdmin != address(0), "TxKeeper: New admin cannot be zero address");
        admin = _newAdmin;
    }
}

